sudo: required

language: bash

services:
  - docker
  - mysql

# safelist
branches:
  only:
    - master
    - production

test:
  adapter: mysql2
  database: mads
  username: root
  encoding: utf8

before_install:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   - docker build -t aaa89/mads-todolist-2017:$TRAVIS_BUILD_NUMBER .
   - docker push aaa89/mads-todolist-2017:$TRAVIS_BUILD_NUMBER
   - docker tag aaa89/mads-todolist-2017:$TRAVIS_BUILD_NUMBER aaa89/mads-todolist-2017:latest
   - docker push aaa89/mads-todolist-2017:latest
   - docker run -d --rm -p 3306:3306 --name play-mysql -e MYSQL_ROOT_PASSWORD=mads -e MYSQL_DATABASE=mads mysql

script:
   - docker run --rm aaa89/mads-todolist-2017:latest /bin/bash -c "sbt test"
   - docker run --link play-mysql:mysql --rm -e DB_URL="jdbc:mysql://play-mysql:3306/mads"  -e DB_USER_NAME="root" -e DB_USER_PASSWD="mads" aaa89/mads-todolist-2017:latest /bin/bash -c "sbt '; set javaOptions += \"-Dconfig.file=conf/integration.conf\"; test'"
